### ISSUE TITLE
License Matrix

### ISSUE THREAD

**Issue by Jamie0** [jasofalcon/matrix#1]
I'd love to re-use your code, but at the moment it's unlicensed. 

Would you consider adding a LICENSE (such as MIT) so that becomes possible?

**Comment by jasofalcon** [comment]
Hi Jamie, of course. Sorry for the late reply, I will try to do it today, is that ok?

**Comment by jasofalcon** [comment]
License created, very similar to MIT.
Hope it's ok with you.
